# Playbook to install nginx installation
# Written in YAML and starts with ---

---

# hosts dName of host 
- hosts: web
# host info 
  gather_facts: yes
# admin access
  become: true

# instructions using task modules
  tasks:

#  - name: sync the app folder
#    synchronize:
#      src: /home/vagrant/environment/app/
#      dest: /home/vagrant/

# Allowing access to port 80/localhost
  - name: Allow all access to tcp port 80
    ufw:
      rule: allow
      port: '80'
      proto: tcp

# Install Dependencies: Nginx,nojs,npm 
  - name: Install Nginx
    apt: pkg=nginx state=present update_cache=yes

  - name: Curl nodejs source
    shell: curl -sL https://deb.nodesource.com/setup_12.x | sudo -E bash -

  - name: Install nodejs
    apt: pkg=nodejs state=present

  - name: Install NPM
    apt: pkg=npm state=present

  - name: Install pm2
    npm:
      name: pm2
      global: yes

# Removes default nginx config file 
  - name: Remove nginx default file
    file:
      path: /etc/nginx/sites-available/default
      state: absent

# Creating new file for nginx conf 
  - name: Create empty file
    file:
      path: /etc/nginx/sites-enabled/reverseproxy.conf
      state: touch# Writing lines in the new nginx conf file 
  - name: Insert nginx configuration for reverse proxy
    blockinfile:
      path: /etc/nginx/sites-enabled/reverseproxy.conf
      backup: yes
      block: |
        server{
          listen 80;

          location / {
              proxy_pass http://localhost:3000;
          }
        }

# Creating a link to the new reverse proxy 
  - name: Create link
    file:
      src: /etc/nginx/sites-enabled/reverseproxy.conf
      dest: /etc/nginx/sites-available/reverseproxy.conf
      state: link

  - name: start app
    shell: |
      cd /home/vagrant/environment/app
      pm2 kill
      pm2 start app.js


  handlers:

  - name: restart nginx
    service: name=nginx state=restarted

  - name: fix_nginx_bug
    become: true
    become_user: root
    shell: |
      systemctl stop nginx
      mkdir /etc/systemd/system/nginx.service.d
      printf "[Service]\nExecStartPost=/bin/sleep 0.1\n" > /home/ubuntu/override.conf
      sudo cp /home/ubuntu/override.conf /etc/systemd/system/nginx.service.d/override$
      sudo systemctl daemon-reload
      sudo systemctl start nginx

